"""initial_database_schema

Revision ID: 93160675bbfa
Revises: 
Create Date: 2025-11-12 11:39:49.197432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93160675bbfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_cep'), 'addresses', ['cep'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('cnpj_registrations',
    sa.Column('qual_seu_negocio', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('seu_nome', sa.String(length=255), nullable=False),
    sa.Column('sua_funcao', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_registrations_cnpj'), 'cnpj_registrations', ['cnpj'], unique=True)
    op.create_index(op.f('ix_cnpj_registrations_email'), 'cnpj_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_cnpj_registrations_id'), 'cnpj_registrations', ['id'], unique=False)
    op.create_table('cpf_registrations',
    sa.Column('perfil_compra', sa.String(length=20), nullable=False),
    sa.Column('qual_negocio_cpf', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpf_registrations_cpf'), 'cpf_registrations', ['cpf'], unique=True)
    op.create_index(op.f('ix_cpf_registrations_email'), 'cpf_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_cpf_registrations_id'), 'cpf_registrations', ['id'], unique=False)
    op.create_table('registration_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('registration_type', sa.String(length=10), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_sessions_id'), 'registration_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_registration_sessions_session_id'), 'registration_sessions', ['session_id'], unique=True)
    op.create_table('organizations',
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cnpj_registration_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cnpj_registration_id'], ['cnpj_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_cnpj'), 'organizations', ['cnpj'], unique=True)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registration_type', sa.String(length=10), nullable=True),
    sa.Column('registration_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_registration_sessions_session_id'), table_name='registration_sessions')
    op.drop_index(op.f('ix_registration_sessions_id'), table_name='registration_sessions')
    op.drop_table('registration_sessions')
    op.drop_index(op.f('ix_cpf_registrations_id'), table_name='cpf_registrations')
    op.drop_index(op.f('ix_cpf_registrations_email'), table_name='cpf_registrations')
    op.drop_index(op.f('ix_cpf_registrations_cpf'), table_name='cpf_registrations')
    op.drop_table('cpf_registrations')
    op.drop_index(op.f('ix_cnpj_registrations_id'), table_name='cnpj_registrations')
    op.drop_index(op.f('ix_cnpj_registrations_email'), table_name='cnpj_registrations')
    op.drop_index(op.f('ix_cnpj_registrations_cnpj'), table_name='cnpj_registrations')
    op.drop_table('cnpj_registrations')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_cep'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
